import './components/example/example';
import './index.scss';
declare class Example {
    private $parent;
    private $sliderWrapper;
    private $sections;
    private slider?;
    private props?;
    private cache;
    constructor(parent: HTMLElement);
    private static prepareFunction;
    private static prepareArray;
    private static isResult;
    private static prepareObject;
    private static prepareJSON;
    private static updateHandle;
    private static updateHandles;
    private static extractFunctionBody;
    private static extractValue;
    private init;
    private initHandlers;
    private initCache;
    private initHandler;
    private getProps;
    private setProps;
    private updateProps;
    private checkNeedUpdate;
    private updateSections;
    private updateSection;
    private onAfterChange;
    private handleSectionClick;
    private handleSectionInput;
    private handleSectionFocusout;
    private getSectionItems;
    private addHandle;
    private removeHandle;
    private processingSection;
    private processingInput;
    private prepareProp;
    private static prepareValue;
}
export default Example;
